language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - /home/travis/.phpenv/versions/5.4/bin/composer self-update
  - composer install --dev --prefer-source --no-interaction

script: vendor/bin/phpspec run